/**
 * This tool's own strings — a tool ships its translations the way an
 * extension does, instead of adding keys to the app's catalogs. Only
 * `en-US` is required; every other locale falls back to it key by key.
 *
 * `name` and `summary` are the two the shelf reads, and the summary is
 * clamped to two lines in every language, so none of them run long.
 *
 * The room's copy has a sense of humour and a tool is welcome to it —
 * except in a name a screen reader announces, in anything that
 * instructs, and in anything about what leaves this browser. The three
 * lines about the server reading a page, about a link signed for one
 * viewer, and about a frame nobody can drive are written flat on
 * purpose: they are the ones somebody may act on.
 */
import type { ToolText } from '../contract';

export const TEXT: ToolText = {
  'en-US': {
    name: 'Video',
    summary: [
      'Watch anything together: paste a page with a video and pick what plays for the room.',
      'Any page with a video in it. Paste the link, choose the source, everybody watches.',
      'A stream, an episode, a lecture. Paste the page and the room watches it with you.',
    ],
    linkLabel: 'Link to a page with a video',
    replaceLabel: 'Watch something else',
    linkPlaceholder: 'https://… — a page, a stream, or a video file',
    find: 'Look for the video',
    looking: 'Reading that page…',
    lookupNote: 'To find the video, the page is fetched and read once. Nothing is stored.',
    invalidUrl: 'That is not a link this can open.',
    unreachable: 'That page did not answer.',
    nothingFound:
      'No video found in that page, and it will not open here either. If you can see it playing, copy the link the player itself uses and paste that.',
    chooseLabel: 'What the room watches',
    open: 'Play for everyone',
    closeForAll: 'Close it for everyone',
    stageLabel: 'Watching together',
    live: 'Live',
    kindFile: 'Video file',
    kindHls: 'Stream',
    kindDash: 'Stream',
    kindTwitch: 'Twitch',
    kindFrame: 'The page itself',
    kindEmbed: 'A player inside it',
    sharedClock: 'Shared clock',
    ownClock: 'Each on their own',
    source: 'from {host}',
    via: 'through {host}',
    personal:
      'This link was signed for whoever opened the page, so it may play for you and for nobody else.',
    failed:
      'This source did not play here. The site may only allow it on its own pages — try another option, or the page itself.',
    openOriginal: 'Open the original page',
    frameNote:
      'The room sees the same page, and each person plays it themselves: no shared clock, and the speaker key does not reach inside it.',
    youtubeHint: 'YouTube has a shelf of its own, and it comes with a shared clock.',
    pickOnPage: 'Pick it on the page…',
    pickHint: 'Opens the page in a window of its own. Press play, and what it loads shows up here.',
    picking: 'Waiting for the page…',
    pickNothing: 'Nothing played in that window. Press play on the page and it will appear here.',
    noHls: 'This browser cannot play that stream.',
  },
  'pt-BR': {
    name: 'Vídeo',
    summary: [
      'Assistam a qualquer coisa: cole uma página com vídeo e escolha o que toca para a sala.',
      'Qualquer página com vídeo. Cole o link, escolha a fonte, todo mundo assiste.',
      'Uma live, um episódio, uma aula. Cole a página e a sala assiste junto com você.',
    ],
    linkLabel: 'Link de uma página com vídeo',
    replaceLabel: 'Passar outra coisa',
    linkPlaceholder: 'https://… — uma página, uma transmissão ou um arquivo',
    find: 'Procurar o vídeo',
    looking: 'Lendo essa página…',
    lookupNote:
      'Para achar o vídeo, a página é buscada e lida uma vez. Nada disso fica guardado.',
    invalidUrl: 'Esse não é um link que dê para abrir.',
    unreachable: 'Essa página não respondeu.',
    nothingFound:
      'Não achei vídeo nessa página, e ela também não abre aqui. Se você consegue ver o vídeo tocando, copie o link que o próprio player usa e cole ele.',
    chooseLabel: 'O que a sala vai assistir',
    open: 'Passar para todos',
    closeForAll: 'Fechar para todos',
    stageLabel: 'Assistindo juntos',
    live: 'Ao vivo',
    kindFile: 'Arquivo de vídeo',
    kindHls: 'Transmissão',
    kindDash: 'Transmissão',
    kindTwitch: 'Twitch',
    kindFrame: 'A própria página',
    kindEmbed: 'Um player dentro dela',
    sharedClock: 'Relógio compartilhado',
    ownClock: 'Cada um no seu',
    source: 'de {host}',
    via: 'por {host}',
    personal:
      'Esse link foi assinado para quem abriu a página, então ele pode tocar para você e para mais ninguém.',
    failed:
      'Essa fonte não tocou aqui. O site pode liberar ela só nas páginas dele — tente outra opção, ou a página em si.',
    openOriginal: 'Abrir a página original',
    frameNote:
      'A sala vê a mesma página, e cada pessoa toca a sua: sem relógio compartilhado, e a tecla de som da sala não alcança lá dentro.',
    youtubeHint: 'O YouTube tem prateleira própria, e ela vem com relógio compartilhado.',
    pickOnPage: 'Escolher na página…',
    pickHint: 'Abre a página numa janela só dela. Aperte play, e o que ela carregar aparece aqui.',
    picking: 'Esperando a página…',
    pickNothing: 'Nada tocou naquela janela. Aperte play na página e a fonte aparece aqui.',
    noHls: 'Este navegador não toca essa transmissão.',
  },
  es: {
    name: 'Video',
    summary: [
      'Vean lo que sea: peguen una página con video y elijan qué suena para la sala.',
      'Cualquier página con video. Pega el enlace, elige la fuente, todos miran.',
      'Un directo, un episodio, una clase. Pega la página y la sala la ve contigo.',
    ],
    linkLabel: 'Enlace de una página con video',
    replaceLabel: 'Poner otra cosa',
    linkPlaceholder: 'https://… — una página, un directo o un archivo',
    find: 'Buscar el video',
    looking: 'Leyendo esa página…',
    lookupNote: 'Para encontrar el video, la página se busca y se lee una vez. No se guarda nada.',
    invalidUrl: 'Ese no es un enlace que se pueda abrir.',
    unreachable: 'Esa página no respondió.',
    nothingFound:
      'No encontré video en esa página, y tampoco se abre aquí. Si lo ves reproduciéndose, copia el enlace que usa el propio reproductor y pégalo.',
    chooseLabel: 'Lo que verá la sala',
    open: 'Poner para todos',
    closeForAll: 'Cerrarlo para todos',
    stageLabel: 'Viendo juntos',
    live: 'En vivo',
    kindFile: 'Archivo de video',
    kindHls: 'Transmisión',
    kindDash: 'Transmisión',
    kindTwitch: 'Twitch',
    kindFrame: 'La página misma',
    kindEmbed: 'Un reproductor dentro de ella',
    sharedClock: 'Reloj compartido',
    ownClock: 'Cada quien el suyo',
    source: 'de {host}',
    via: 'por {host}',
    personal:
      'Este enlace fue firmado para quien abrió la página, así que puede reproducirse para ti y para nadie más.',
    failed:
      'Esta fuente no se reprodujo aquí. El sitio puede permitirla solo en sus propias páginas: prueba otra opción, o la página misma.',
    openOriginal: 'Abrir la página original',
    frameNote:
      'La sala ve la misma página y cada persona la reproduce por su cuenta: sin reloj compartido, y la tecla de sonido de la sala no llega ahí dentro.',
    youtubeHint: 'YouTube tiene su propio estante, y ese sí trae reloj compartido.',
    pickOnPage: 'Elegirlo en la página…',
    pickHint: 'Abre la página en una ventana propia. Dale play y lo que cargue aparece aquí.',
    picking: 'Esperando la página…',
    pickNothing: 'No sonó nada en esa ventana. Dale play en la página y aparecerá aquí.',
    noHls: 'Este navegador no puede reproducir esa transmisión.',
  },
  'zh-CN': {
    name: '视频',
    summary: [
      '一起看任何东西：贴一个有视频的页面，挑一个放给整个房间。',
      '任何带视频的页面。贴上链接，选好来源，大家一起看。',
      '一场直播、一集番、一节课。贴上页面，房间陪你一起看。',
    ],
    linkLabel: '含视频页面的链接',
    replaceLabel: '换一个来看',
    linkPlaceholder: 'https://… — 页面、直播或视频文件',
    find: '找出视频',
    looking: '正在读这个页面…',
    lookupNote: '为了找到视频，这个页面会被抓取并读取一次。什么都不会保存。',
    invalidUrl: '这个链接打不开。',
    unreachable: '这个页面没有响应。',
    nothingFound:
      '这个页面里没找到视频，它也无法在这里打开。如果你能看到视频在播放，请复制播放器自己用的那个链接，贴过来。',
    chooseLabel: '房间要看的内容',
    open: '放给所有人',
    closeForAll: '为所有人关闭',
    stageLabel: '一起观看',
    live: '直播',
    kindFile: '视频文件',
    kindHls: '直播流',
    kindDash: '直播流',
    kindTwitch: 'Twitch',
    kindFrame: '页面本身',
    kindEmbed: '页面里的播放器',
    sharedClock: '共享进度',
    ownClock: '各看各的',
    source: '来自 {host}',
    via: '经由 {host}',
    personal: '这个链接是为打开页面的那个人签发的，可能只有你能播放。',
    failed: '这个来源在这里没能播放。站点可能只允许它在自家页面上播——换一个选项，或者用页面本身。',
    openOriginal: '打开原页面',
    frameNote: '房间看到同一个页面，各自播放：没有共享进度，房间的声音键也伸不进去。',
    youtubeHint: 'YouTube 有自己的一格，那个自带共享进度。',
    pickOnPage: '在页面里挑…',
    pickHint: '会用单独的窗口打开这个页面。按下播放，它加载的内容就会出现在这里。',
    picking: '等待页面…',
    pickNothing: '那个窗口里什么都没播。在页面上按播放，来源就会出现在这里。',
    noHls: '这个浏览器播不了该直播流。',
  },
  ja: {
    name: '動画',
    summary: [
      '何でもいっしょに。動画のあるページを貼って、部屋に流すものを選ぶだけ。',
      '動画があるページなら何でも。リンクを貼り、ソースを選べば、全員で観られます。',
      '配信でも、一話でも、講義でも。ページを貼れば、部屋がいっしょに観ます。',
    ],
    linkLabel: '動画のあるページのリンク',
    replaceLabel: '別のものを流す',
    linkPlaceholder: 'https://… — ページ、配信、動画ファイル',
    find: '動画を探す',
    looking: 'そのページを読んでいます…',
    lookupNote: '動画を見つけるため、ページを一度だけ取得して読みます。何も保存しません。',
    invalidUrl: 'これは開けるリンクではありません。',
    unreachable: 'そのページは応答しませんでした。',
    nothingFound:
      'そのページに動画は見つからず、ここで開くこともできません。再生されているのが見えているなら、プレーヤー自身が使っているリンクをコピーして貼ってください。',
    chooseLabel: '部屋で観るもの',
    open: '全員に流す',
    closeForAll: '全員の画面で閉じる',
    stageLabel: 'いっしょに視聴中',
    live: 'ライブ',
    kindFile: '動画ファイル',
    kindHls: '配信',
    kindDash: '配信',
    kindTwitch: 'Twitch',
    kindFrame: 'ページそのもの',
    kindEmbed: 'ページ内のプレーヤー',
    sharedClock: '再生位置を共有',
    ownClock: '各自で操作',
    source: '{host} から',
    via: '{host} 経由',
    personal:
      'このリンクはページを開いた人に向けて署名されています。あなただけ再生できて、ほかの人には再生できないことがあります。',
    failed:
      'このソースはここでは再生できませんでした。サイトが自分のページでしか許可していない可能性があります。別の候補か、ページそのものを試してください。',
    openOriginal: '元のページを開く',
    frameNote:
      '部屋は同じページを見て、再生は各自で行います。再生位置は共有されず、部屋のスピーカーキーも中には届きません。',
    youtubeHint: 'YouTube には専用の棚があり、そちらは再生位置を共有できます。',
    pickOnPage: 'ページ上で選ぶ…',
    pickHint: 'ページを専用のウィンドウで開きます。再生を押すと、読み込まれたものがここに出ます。',
    picking: 'ページを待っています…',
    pickNothing: 'そのウィンドウでは何も再生されませんでした。ページで再生を押すとここに出ます。',
    noHls: 'このブラウザではその配信を再生できません。',
  },
};
