/**
 * This tool's own strings — a tool ships its translations the way an
 * extension does, instead of adding keys to the app's catalogs. Only
 * `en-US` is required; every other locale falls back to it key by key, so
 * a tool may ship one language and still work everywhere.
 *
 * `name` and `summary` are the two the shelf reads, and the summary is
 * clamped to two lines in every language, so none of them run long. A
 * list is a set of variants, drawn once per page load.
 *
 * The room's copy has a sense of humour and a tool is welcome to it —
 * except in a name a screen reader announces, in anything that
 * instructs, and in anything about what leaves this browser. The lines
 * about the server reading a page, about a link signed for one viewer,
 * and about a frame nobody can drive are written flat on purpose: they
 * are the ones somebody may act on.
 */
import type { ToolText } from '../contract';

export const TEXT: ToolText = {
  'en-US': {
    name: 'Watch together',
    summary: [
      'A video for the whole room — YouTube or anything else. Anyone can play, pause and skip.',
      'Paste a link. YouTube, a stream, a page with a film in it: one room, one timeline.',
      'One video, one position, no “wait, where are you?”. Anyone can drive, anyone can queue.',
    ],
    linkLabel: 'A link to watch',
    addLabel: 'Add something else',
    linkPlaceholder: 'https://… — YouTube, a page, a stream or a video file',
    find: 'Look for the video',
    looking: 'Reading that page…',
    lookupNote: 'A page is fetched and read once. Nothing is stored.',
    invalidUrl: 'That is not a link this can open.',
    unreachable: 'That page did not answer.',
    refused: 'That site would not let this read it. Press play there and paste the link its player uses.',
    nothingFound: 'No video in that page. If you can see it playing, paste the link its player uses.',
    chooseLabel: 'What the room watches',
    open: 'Play for everyone',
    playNow: 'Play now',
    addToQueue: 'Add to the queue',
    closeForAll: 'Close it for everyone',
    queueTitle: { one: 'Next up ({count})', other: 'Next up ({count})' },
    queueEmpty: 'Nothing lined up after this one.',
    queueFull: 'The queue is full — take something out to line up more.',
    queued: { one: '· {count} lined up', other: '· {count} lined up' },
    skip: 'Skip to the next one',
    playThis: 'Play this one now',
    removeThis: 'Take it out of the queue',
    thumbAlt: 'Thumbnail of the queued video',
    live: 'Live',
    kindYouTube: 'YouTube video',
    kindList: 'YouTube playlist',
    kindFile: 'Video file',
    kindHls: 'Stream',
    kindDash: 'Stream',
    kindTwitch: 'Twitch',
    kindFrame: 'The page itself',
    kindEmbed: 'A player inside it',
    sharedClock: 'Shared clock',
    liveTogether: 'Live, in step',
    ownClock: 'Each on their own',
    source: 'from {host}',
    via: 'through {host}',
    personal: 'Signed for whoever opened the page: it may play for you and for nobody else.',
    pickOnPage: 'Pick it on the page…',
    pickHint: 'Opens the page in its own window. Press play there and it turns up here.',
    picking: 'Waiting for the page…',
    pickNothing: 'Nothing played in that window.',
    stageLabel: 'Watching together',
    blocked: 'YouTube will not play this here: private, removed, or embedding off.',
    openOnYouTube: 'Open it on YouTube',
    failed: 'This did not play here — the site may only allow it on its own pages.',
    noHls: 'This browser cannot play that stream.',
    openOriginal: 'Open the original page',
    frameNote: 'Same page for everyone, each playing their own. The speaker key does not reach inside.',
  },
  'pt-BR': {
    name: 'Assistir juntos',
    summary: [
      'Um vídeo para a sala inteira — YouTube ou qualquer outra coisa. Qualquer um dá play, pausa e pula.',
      'Cole um link. YouTube, uma live, uma página com filme: uma sala, uma linha do tempo.',
      'Um vídeo, uma posição, sem “peraí, você está em que minuto?”. Qualquer um controla e põe na fila.',
    ],
    linkLabel: 'Um link para assistir',
    addLabel: 'Pôr outra coisa',
    linkPlaceholder: 'https://… — YouTube, uma página, uma transmissão ou um arquivo',
    find: 'Procurar o vídeo',
    looking: 'Lendo essa página…',
    lookupNote: 'A página é buscada e lida uma vez. Nada fica guardado.',
    invalidUrl: 'Esse não é um link que dê para abrir.',
    unreachable: 'Essa página não respondeu.',
    refused: 'Esse site não deixou a leitura acontecer. Aperte play lá e cole o link que o player dele usa.',
    nothingFound: 'Nenhum vídeo nessa página. Se você vê ele tocando, cole o link que o player usa.',
    chooseLabel: 'O que a sala vai assistir',
    open: 'Passar para todos',
    playNow: 'Passar agora',
    addToQueue: 'Pôr na fila',
    closeForAll: 'Fechar para todos',
    queueTitle: { one: 'Na fila ({count})', other: 'Na fila ({count})' },
    queueEmpty: 'Nada na fila depois deste.',
    queueFull: 'A fila está cheia — tire alguma coisa para pôr mais.',
    queued: { one: '· {count} na fila', other: '· {count} na fila' },
    skip: 'Pular para o próximo',
    playThis: 'Passar este agora',
    removeThis: 'Tirar da fila',
    thumbAlt: 'Miniatura do vídeo na fila',
    live: 'Ao vivo',
    kindYouTube: 'Vídeo do YouTube',
    kindList: 'Playlist do YouTube',
    kindFile: 'Arquivo de vídeo',
    kindHls: 'Transmissão',
    kindDash: 'Transmissão',
    kindTwitch: 'Twitch',
    kindFrame: 'A própria página',
    kindEmbed: 'Um player dentro dela',
    sharedClock: 'Relógio compartilhado',
    liveTogether: 'Ao vivo, juntos',
    ownClock: 'Cada um no seu',
    source: 'de {host}',
    via: 'por {host}',
    personal: 'Assinado para quem abriu a página: pode tocar para você e para mais ninguém.',
    pickOnPage: 'Escolher na página…',
    pickHint: 'Abre a página numa janela só dela. Aperte play lá e aparece aqui.',
    picking: 'Esperando a página…',
    pickNothing: 'Nada tocou naquela janela.',
    stageLabel: 'Assistindo juntos',
    blocked: 'O YouTube não toca este aqui: privado, removido ou sem incorporação.',
    openOnYouTube: 'Abrir no YouTube',
    failed: 'Isso não tocou aqui — o site pode liberar só nas páginas dele.',
    noHls: 'Este navegador não toca essa transmissão.',
    openOriginal: 'Abrir a página original',
    frameNote: 'A mesma página para todos, cada um tocando a sua. A tecla de som não alcança lá dentro.',
  },
  es: {
    name: 'Ver juntos',
    summary: [
      'Un video para toda la sala — YouTube o lo que sea. Cualquiera da play, pausa y salta.',
      'Pega un enlace. YouTube, un directo, una página con película: una sala, una línea de tiempo.',
      'Un video, una posición, sin “espera, ¿en qué minuto vas?”. Cualquiera controla y encola.',
    ],
    linkLabel: 'Un enlace para ver',
    addLabel: 'Poner otra cosa',
    linkPlaceholder: 'https://… — YouTube, una página, un directo o un archivo',
    find: 'Buscar el video',
    looking: 'Leyendo esa página…',
    lookupNote: 'La página se busca y se lee una vez. No se guarda nada.',
    invalidUrl: 'Ese no es un enlace que se pueda abrir.',
    unreachable: 'Esa página no respondió.',
    refused: 'Ese sitio no dejó que lo leyéramos. Dale play ahí y pega el enlace que usa su reproductor.',
    nothingFound: 'Ningún video en esa página. Si lo ves reproduciéndose, pega el enlace que usa su reproductor.',
    chooseLabel: 'Lo que verá la sala',
    open: 'Poner para todos',
    playNow: 'Poner ahora',
    addToQueue: 'Poner en la cola',
    closeForAll: 'Cerrarlo para todos',
    queueTitle: { one: 'En cola ({count})', other: 'En cola ({count})' },
    queueEmpty: 'No hay nada en cola después de este.',
    queueFull: 'La cola está llena: quita algo para poner más.',
    queued: { one: '· {count} en cola', other: '· {count} en cola' },
    skip: 'Saltar al siguiente',
    playThis: 'Poner este ahora',
    removeThis: 'Quitar de la cola',
    thumbAlt: 'Miniatura del video en cola',
    live: 'En vivo',
    kindYouTube: 'Video de YouTube',
    kindList: 'Lista de YouTube',
    kindFile: 'Archivo de video',
    kindHls: 'Transmisión',
    kindDash: 'Transmisión',
    kindTwitch: 'Twitch',
    kindFrame: 'La página misma',
    kindEmbed: 'Un reproductor dentro de ella',
    sharedClock: 'Reloj compartido',
    liveTogether: 'En vivo, a la vez',
    ownClock: 'Cada quien el suyo',
    source: 'de {host}',
    via: 'por {host}',
    personal: 'Firmado para quien abrió la página: puede reproducirse para ti y para nadie más.',
    pickOnPage: 'Elegirlo en la página…',
    pickHint: 'Abre la página en una ventana propia. Dale play ahí y aparece aquí.',
    picking: 'Esperando la página…',
    pickNothing: 'No sonó nada en esa ventana.',
    stageLabel: 'Viendo juntos',
    blocked: 'YouTube no reproduce este aquí: privado, eliminado o sin incrustación.',
    openOnYouTube: 'Abrirlo en YouTube',
    failed: 'Esto no se reprodujo aquí: el sitio puede permitirlo solo en sus propias páginas.',
    noHls: 'Este navegador no puede reproducir esa transmisión.',
    openOriginal: 'Abrir la página original',
    frameNote: 'La misma página para todos, cada quien reproduce la suya. La tecla de sonido no llega ahí dentro.',
  },
  'zh-CN': {
    name: '一起看',
    summary: [
      '整个房间共用一个视频——YouTube 或别的什么都行。谁都可以播放、暂停、跳过。',
      '贴一个链接。YouTube、直播、带片子的页面：一个房间，一条时间轴。',
      '一个视频、一个进度，不用再问“你放到哪儿了”。谁都能控制，谁都能排队。',
    ],
    linkLabel: '要一起看的链接',
    addLabel: '换点别的',
    linkPlaceholder: 'https://… — YouTube、页面、直播或视频文件',
    find: '找出视频',
    looking: '正在读这个页面…',
    lookupNote: '页面会被抓取并读取一次。什么都不会保存。',
    invalidUrl: '这个链接打不开。',
    unreachable: '这个页面没有响应。',
    refused: '这个站点不允许我们读取它。在那里按播放，把播放器用的链接贴过来。',
    nothingFound: '这个页面里没有视频。如果你看到它在播放，贴上播放器用的链接。',
    chooseLabel: '房间要看的内容',
    open: '放给所有人',
    playNow: '现在就放',
    addToQueue: '加入队列',
    closeForAll: '为所有人关闭',
    queueTitle: { other: '队列中（{count}）' },
    queueEmpty: '这个之后没有排任何东西。',
    queueFull: '队列满了——先移走一个再排。',
    queued: { other: '· 队列 {count}' },
    skip: '跳到下一个',
    playThis: '现在放这个',
    removeThis: '从队列中移除',
    thumbAlt: '队列中视频的缩略图',
    live: '直播',
    kindYouTube: 'YouTube 视频',
    kindList: 'YouTube 播放列表',
    kindFile: '视频文件',
    kindHls: '直播流',
    kindDash: '直播流',
    kindTwitch: 'Twitch',
    kindFrame: '页面本身',
    kindEmbed: '页面里的播放器',
    sharedClock: '共享进度',
    liveTogether: '同步直播',
    ownClock: '各看各的',
    source: '来自 {host}',
    via: '经由 {host}',
    personal: '为打开页面的人签发：可能只有你能播放。',
    pickOnPage: '在页面里挑…',
    pickHint: '会用单独的窗口打开页面。在那里按播放，就会出现在这里。',
    picking: '等待页面…',
    pickNothing: '那个窗口里什么都没播。',
    stageLabel: '一起观看',
    blocked: 'YouTube 无法在这里播放：私享、已删除，或不允许嵌入。',
    openOnYouTube: '在 YouTube 中打开',
    failed: '这里没能播放——站点可能只允许它在自家页面上播。',
    noHls: '这个浏览器播不了该直播流。',
    openOriginal: '打开原页面',
    frameNote: '同一个页面，各自播放。房间的声音键伸不进去。',
  },
  ja: {
    name: 'いっしょに観る',
    summary: [
      '部屋みんなでひとつの動画——YouTube でも、それ以外でも。再生も一時停止もスキップも誰でも。',
      'リンクを貼るだけ。YouTube、配信、動画のあるページ。ひとつの部屋に、ひとつの時間軸。',
      '動画もいまの位置もひとつ。「どこまで見た？」はもう不要。操作もキューも誰でも。',
    ],
    linkLabel: 'いっしょに観るリンク',
    addLabel: '別のものを流す',
    linkPlaceholder: 'https://… — YouTube、ページ、配信、動画ファイル',
    find: '動画を探す',
    looking: 'そのページを読んでいます…',
    lookupNote: 'ページを一度だけ取得して読みます。何も保存しません。',
    invalidUrl: 'これは開けるリンクではありません。',
    unreachable: 'そのページは応答しませんでした。',
    refused: 'そのサイトは読み取りを許可しませんでした。そちらで再生を押し、プレーヤーのリンクを貼ってください。',
    nothingFound: 'そのページに動画はありません。再生が見えているなら、プレーヤーのリンクを貼ってください。',
    chooseLabel: '部屋で観るもの',
    open: '全員に流す',
    playNow: 'いま流す',
    addToQueue: 'キューに入れる',
    closeForAll: '全員の画面で閉じる',
    queueTitle: { other: 'キュー（{count}）' },
    queueEmpty: 'この後に控えているものはありません。',
    queueFull: 'キューがいっぱいです。ひとつ外すと追加できます。',
    queued: { other: '· キュー {count}' },
    skip: '次へ',
    playThis: 'これをいま流す',
    removeThis: 'キューから外す',
    thumbAlt: 'キュー内の動画のサムネイル',
    live: 'ライブ',
    kindYouTube: 'YouTube の動画',
    kindList: 'YouTube のプレイリスト',
    kindFile: '動画ファイル',
    kindHls: '配信',
    kindDash: '配信',
    kindTwitch: 'Twitch',
    kindFrame: 'ページそのもの',
    kindEmbed: 'ページ内のプレーヤー',
    sharedClock: '再生位置を共有',
    liveTogether: 'ライブで足並みを',
    ownClock: '各自で操作',
    source: '{host} から',
    via: '{host} 経由',
    personal: 'ページを開いた人に向けた署名付きリンクです。あなただけ再生できることがあります。',
    pickOnPage: 'ページ上で選ぶ…',
    pickHint: 'ページを専用のウィンドウで開きます。そこで再生を押すとここに出ます。',
    picking: 'ページを待っています…',
    pickNothing: 'そのウィンドウでは何も再生されませんでした。',
    stageLabel: 'いっしょに視聴中',
    blocked: 'YouTube はここで再生しません（限定公開・削除済み・埋め込み不可）。',
    openOnYouTube: 'YouTube で開く',
    failed: 'ここでは再生できませんでした。サイトが自分のページでしか許可していない可能性があります。',
    noHls: 'このブラウザではその配信を再生できません。',
    openOriginal: '元のページを開く',
    frameNote: '同じページを全員で、再生は各自。スピーカーキーは中に届きません。',
  },
};
