/**
 * This tool's own strings — a tool ships its translations the way an
 * extension does, instead of adding keys to the app's catalogs. Only
 * `en-US` is required; every other locale falls back to it key by key.
 *
 * `name` and `summary` are the two the shelf reads, and a list is a set
 * of variants drawn once per page load. The room's copy has a sense of
 * humour and a tool is welcome to it — except in a name a screen reader
 * announces, in anything that instructs, and in the two lines that say
 * what this tool does NOT do: `ownPlay` and `account`. Those are written
 * flat on purpose, because somebody is going to act on them.
 */
import type { ToolText } from '../contract';

export const TEXT: ToolText = {
  'en-US': {
    name: 'Spotify',
    summary: [
      'Listen together: put a song or a playlist on the room and everyone gets the same player.',
      'Pass the aux around. Anyone puts something on, anyone lines up what comes next.',
      'A song, a record, a playlist — the room all looking at the same thing.',
    ],
    linkLabel: 'Spotify link',
    addLabel: 'Add another Spotify link',
    linkPlaceholder: 'https://open.spotify.com/…',
    open: 'Put it on for everyone',
    addToQueue: 'Add to the queue',
    playNow: 'Put it on now',
    invalid: 'No Spotify link in there. Copy the one that starts with open.spotify.com — a spotify.link address does not say what it points at.',
    queueTitle: { one: 'Next up ({count})', other: 'Next up ({count})' },
    queueEmpty: 'Nothing lined up after this one.',
    queueFull: 'The queue is full at {max}.',
    queued: { one: '· {count} lined up', other: '· {count} lined up' },
    skip: 'On to the next one',
    playThis: 'Put this one on now',
    removeThis: 'Take it out of the queue',
    closeForAll: 'Close it for everyone',
    stageLabel: 'Listening together',
    putOn: 'put on by {name}',
    kindTrack: 'Song',
    kindAlbum: 'Album',
    kindPlaylist: 'Playlist',
    kindArtist: 'Artist',
    kindEpisode: 'Episode',
    kindShow: 'Podcast',
    ownPlay:
      'Everyone gets the same player and presses play on their own copy. This tool never reaches into Spotify, so the room agrees on what is on, not on the second it is at.',
    account:
      'Each person plays from their own Spotify: signed in to Spotify in this browser, the whole thing; signed out, the 30-second preview Spotify hands out.',
    openOnSpotify: 'Open on Spotify',
    speakersOff: 'Your speakers are off, so the player is not here.',
    speakersOffHint: 'Turn the room’s speakers back on to bring it back.',
  },
  'pt-BR': {
    name: 'Spotify',
    summary: [
      'Ouçam juntos: ponha uma música ou uma playlist na sala e todo mundo recebe o mesmo player.',
      'Passe o aux adiante. Qualquer um põe algo para tocar, qualquer um enfileira o que vem depois.',
      'Uma música, um disco, uma playlist — a sala inteira olhando para a mesma coisa.',
    ],
    linkLabel: 'Link do Spotify',
    addLabel: 'Adicionar outro link do Spotify',
    linkPlaceholder: 'https://open.spotify.com/…',
    open: 'Pôr para todos',
    addToQueue: 'Pôr na fila',
    playNow: 'Pôr agora',
    invalid: 'Não há um link do Spotify aí. Copie o que começa com open.spotify.com — um endereço spotify.link não diz para onde aponta.',
    queueTitle: { one: 'Na fila ({count})', other: 'Na fila ({count})' },
    queueEmpty: 'Nada na fila depois desta.',
    queueFull: 'A fila está cheia em {max}.',
    queued: { one: '· {count} na fila', other: '· {count} na fila' },
    skip: 'Ir para a próxima',
    playThis: 'Pôr esta agora',
    removeThis: 'Tirar da fila',
    closeForAll: 'Fechar para todos',
    stageLabel: 'Ouvindo juntos',
    putOn: 'posto por {name}',
    kindTrack: 'Música',
    kindAlbum: 'Álbum',
    kindPlaylist: 'Playlist',
    kindArtist: 'Artista',
    kindEpisode: 'Episódio',
    kindShow: 'Podcast',
    ownPlay:
      'Todo mundo recebe o mesmo player e dá play na própria cópia. Esta ferramenta não mexe no Spotify de ninguém, então a sala combina o que está tocando, não o segundo em que está.',
    account:
      'Cada pessoa toca do próprio Spotify: com a conta conectada neste navegador, a faixa inteira; sem ela, a prévia de 30 segundos que o Spotify libera.',
    openOnSpotify: 'Abrir no Spotify',
    speakersOff: 'Suas caixas estão desligadas, então o player não fica aqui.',
    speakersOffHint: 'Ligue o som da sala de novo para trazer o player de volta.',
  },
  es: {
    name: 'Spotify',
    summary: [
      'Escuchen juntos: pon una canción o una lista en la sala y todos reciben el mismo reproductor.',
      'Pasa el aux. Cualquiera pone algo, cualquiera arma lo que viene después.',
      'Una canción, un disco, una lista — toda la sala mirando lo mismo.',
    ],
    linkLabel: 'Enlace de Spotify',
    addLabel: 'Agregar otro enlace de Spotify',
    linkPlaceholder: 'https://open.spotify.com/…',
    open: 'Poner para todos',
    addToQueue: 'Poner en la cola',
    playNow: 'Poner ahora',
    invalid: 'Ahí no hay un enlace de Spotify. Copia el que empieza con open.spotify.com — una dirección spotify.link no dice a dónde apunta.',
    queueTitle: { one: 'En cola ({count})', other: 'En cola ({count})' },
    queueEmpty: 'No hay nada en cola después de esta.',
    queueFull: 'La cola está llena en {max}.',
    queued: { one: '· {count} en cola', other: '· {count} en cola' },
    skip: 'Ir a la siguiente',
    playThis: 'Poner esta ahora',
    removeThis: 'Quitar de la cola',
    closeForAll: 'Cerrarlo para todos',
    stageLabel: 'Escuchando juntos',
    putOn: 'puesto por {name}',
    kindTrack: 'Canción',
    kindAlbum: 'Álbum',
    kindPlaylist: 'Lista',
    kindArtist: 'Artista',
    kindEpisode: 'Episodio',
    kindShow: 'Pódcast',
    ownPlay:
      'Todos reciben el mismo reproductor y le dan play en su propia copia. Esta herramienta no entra en el Spotify de nadie, así que la sala acuerda qué suena, no en qué segundo va.',
    account:
      'Cada persona escucha desde su propio Spotify: con la sesión iniciada en este navegador, la pista completa; sin ella, la vista previa de 30 segundos que da Spotify.',
    openOnSpotify: 'Abrir en Spotify',
    speakersOff: 'Tus altavoces están apagados, así que el reproductor no está aquí.',
    speakersOffHint: 'Vuelve a encender el sonido de la sala para traerlo de vuelta.',
  },
  'zh-CN': {
    name: 'Spotify',
    summary: [
      '一起听：把一首歌或一个歌单放进房间，所有人都拿到同一个播放器。',
      '把 aux 线传下去。谁都能放，谁都能排下一首。',
      '一首歌、一张专辑、一个歌单——整个房间看着同一样东西。',
    ],
    linkLabel: 'Spotify 链接',
    addLabel: '再添加一个 Spotify 链接',
    linkPlaceholder: 'https://open.spotify.com/…',
    open: '放给所有人',
    addToQueue: '加入队列',
    playNow: '现在就放',
    invalid: '这里没有 Spotify 链接。请复制以 open.spotify.com 开头的那个——spotify.link 短链接不会说明它指向什么。',
    queueTitle: { other: '队列中（{count}）' },
    queueEmpty: '这个之后没有排任何东西。',
    queueFull: '队列已满（{max}）。',
    queued: { other: '· 队列 {count}' },
    skip: '下一个',
    playThis: '现在放这个',
    removeThis: '从队列中移除',
    closeForAll: '为所有人关闭',
    stageLabel: '一起听',
    putOn: '由 {name} 放的',
    kindTrack: '歌曲',
    kindAlbum: '专辑',
    kindPlaylist: '歌单',
    kindArtist: '艺人',
    kindEpisode: '单集',
    kindShow: '播客',
    ownPlay:
      '所有人拿到同一个播放器，各自按下播放。本工具不会去操作任何人的 Spotify，所以房间统一的是“放什么”，而不是“放到第几秒”。',
    account:
      '每个人都用自己的 Spotify 播放：在本浏览器登录了 Spotify，就是完整内容；没登录，就是 Spotify 提供的 30 秒试听。',
    openOnSpotify: '在 Spotify 中打开',
    speakersOff: '你的扬声器已关闭，所以播放器不在这里。',
    speakersOffHint: '重新打开房间的声音即可把它带回来。',
  },
  ja: {
    name: 'Spotify',
    summary: [
      'いっしょに聴く。曲やプレイリストを部屋に置けば、全員に同じプレーヤーが届きます。',
      'AUX ケーブルを回す感覚で。誰でもかけられて、誰でも次を並べられます。',
      '一曲、一枚、一プレイリスト——部屋のみんなが同じものを見ています。',
    ],
    linkLabel: 'Spotify のリンク',
    addLabel: 'Spotify のリンクをもう一つ追加',
    linkPlaceholder: 'https://open.spotify.com/…',
    open: '全員にかける',
    addToQueue: 'キューに入れる',
    playNow: 'いまかける',
    invalid: 'Spotify のリンクが見つかりません。open.spotify.com で始まるものをコピーしてください（spotify.link の短縮アドレスは行き先が書かれていません）。',
    queueTitle: { other: 'キュー（{count}）' },
    queueEmpty: 'この後に控えているものはありません。',
    queueFull: 'キューは {max} で満杯です。',
    queued: { other: '· キュー {count}' },
    skip: '次へ',
    playThis: 'これをいまかける',
    removeThis: 'キューから外す',
    closeForAll: '全員のぶんを閉じる',
    stageLabel: 'いっしょに再生中',
    putOn: '{name} さんがかけました',
    kindTrack: '曲',
    kindAlbum: 'アルバム',
    kindPlaylist: 'プレイリスト',
    kindArtist: 'アーティスト',
    kindEpisode: 'エピソード',
    kindShow: 'ポッドキャスト',
    ownPlay:
      '全員に同じプレーヤーが届き、再生は各自で押します。このツールは誰の Spotify にも触れないので、部屋が合わせるのは「何をかけているか」であって「何秒目か」ではありません。',
    account:
      '再生は各自の Spotify から行われます。このブラウザで Spotify にログインしていれば全編、していなければ Spotify が公開している 30 秒のプレビューです。',
    openOnSpotify: 'Spotify で開く',
    speakersOff: 'スピーカーがオフなので、プレーヤーはここにはありません。',
    speakersOffHint: '部屋の音を戻すと、プレーヤーも戻ります。',
  },
};
